### ISSUE TITLE
SaberFactions Hook

### ISSUE THREAD

**Issue by XragonX147** [Jikoo/Regionerator#101]
Hey,

first off all AWESOME Plugin!
I don't know wheres the right place to ask this, so I will do it here.
Could you add a Hook for the Faction Claims from the SaberFaction Plugin?

That could really help me out

Thank you :)

**Comment by Jikoo** [comment]
SaberFactions appears to identify itself as Factions. That means the existing Factions hook probably works. If it doesn't, please raise an issue including startup logs with debug on at least `MEDIUM`.
