### ISSUE TITLE
Factions Hook with SaberFactions

### ISSUE THREAD

**Issue by XragonX147** [Jikoo/Regionerator#102]
Hey,

as you told me, I raised a new issue with the issue with my startup logs.
I have set the debug level on MEDIUM.
Please tell me, if you need more information.

[latest.log](https://github.com/Jikoo/Regionerator/files/7717695/latest.log)

Thank you :)

**Comment by Jikoo** [comment]
This was fixed in 699e5e008b155d334ad79c92bf51030be8bcbedc, please update to a dev build off [the CI](https://ci.appveyor.com/project/Jikoo/regionerator/build/artifacts).

Probably should make a release soonish though, there've been several minor improvements.
