### ISSUE TITLE
Feature request: BentoBox support

### ISSUE THREAD

**Issue by Leonardo-DGS** [Jikoo/Regionerator#11]
Add BentoBox protection support

**Comment by Jikoo** [comment]
Do you have a link to that plugin? A quick search is just pulling up dead links.

**Comment by leonardo-dgs** [comment]
@Jikoo https://github.com/BentoBoxWorld/BentoBox

**Comment by Jikoo** [comment]
Had a brief look into this. Do you know when an island would be considered to exist but not have an owner?
Given how Regionerator currently works it may be best to ignore all existing islands, owned or not, though it would technically be possible to abandon unowned islands.

**Comment by Jikoo** [comment]
Actually, poking further, it really seems like BentoBox has the capacity to clean itself up pretty well. Fully empty chunks don't consume much disk space at all.
Are you actually experiencing disk space issues? Frankly, you probably don't need Regionerator in any BentoBox-managed worlds assuming abandoned islands are actually deleted.
I can support it, but I sincerely doubt you'll get any tangible benefits.

**Comment by Leonardo-DGS** [comment]
@Jikoo It would be useful for deleting chunks where there aren't any islands.

**Comment by Jikoo** [comment]
Given that BentoBox cleans up abandoned islands quite well by replacing all blocks with air, I am going to decline based on the available API. An entire region filled with air should consume a couple kb max.
In ASkyBlock, islands were available on a per-chunk basis. BentoBox's island system supports variable radii, but does not offer a method for discovering islands based on a location range.

My options for a hook are as follows:
 * Create a dummy island consuming a chunk and see if that can be added to the grid
   * If this fails (the chunk is actually an Island) BentoBox will create several log entries. Logging requires a lot of resources and will cause lag in addition to making log files unreadable.
 * Check numerous locations across a chunk and hope to hit any islands
   * This is unreliable and probably cannot be refined - island radius depends on settings of whatever gamemode is running the world. I'm unwilling to create another horrendous mess like the Towny hook, which checks up to 256 locations per chunk for protections.
 * Check every island until I find a match
   * This is very inefficient and will cause lag.
 * Re-cache all islands to implement my own lookups
   * This is the only reliable and performant method, however, it's kind of a waste when BentoBox could expose the same cached data quite easily.
