### ISSUE TITLE
PlotSquared Compatibility

### ISSUE THREAD

**Issue by lokka30** [Jikoo/Regionerator#112]
Hi, does Regionerator have compatibility with PlotSquared?

As a side note, I recommend enabling Discussions on this repo :)

**Comment by Jikoo** [comment]
Supported plugins are on the [Hooks wiki page](https://github.com/Jikoo/Regionerator/wiki/Hooks) (which I guess needs more discoverability, added to the sidebar). At this time, no, though I'm willing to look into it.

Discussions are enabled, and have been since Discussions exited closed beta.

**Comment by lokka30** [comment]
Thank you Jikoo!
