### ISSUE TITLE
add Residence Support

### ISSUE THREAD

**Issue by Pan1sT** [Jikoo/Regionerator#116]
It seems dropped a year ago? Would you gonna hook it again? Thanks <3

**Comment by Jikoo** [comment]
Sorry, Residence does not meet [my requirements](https://github.com/Jikoo/Regionerator/wiki/Hooks#adding-support) for adding support. You can ask the developer to add their own hook to Regionerator. The old Residence hook can be found [here](https://github.com/Jikoo/Regionerator/blob/30bd5c4dbf3fc9b2c9b1836e76701de59534ef0a/src/main/java/com/github/jikoo/regionerator/hooks/ResidenceHook.java).
