### ISSUE TITLE
Pool Bukkit scheduler usage to reduce thread consumption

### ISSUE THREAD

**Issue by msmanui** [Jikoo/Regionerator#139]
So i've been using Regionator for the first week and i didnt experience any issue, and i think after a week it started to delete inactive regions. However, after that, server would crash randomly to the point that it wont restart automatically (Kind of a freeze). I didnt know what was caused by but i did remove Regionerator and the crash didnt happend any longer. I know its Regionerator because after/before having the server doesnt crash. And it was happening in the 4 survivals servers.

What any other info you would need? Here is the full crash

[full.zip](https://github.com/Jikoo/Regionerator/files/9534594/full.zip)

**Comment by Jikoo** [comment]
Looks like your various SQL connectors are simultaneously failing due to a lack of available threads. I suppose the best thing to do here from Regionerator's end would be to create a pooling system for chunk generation flags instead of raw Bukkit scheduler usage, but this is primarily a case of your system's user file limit being too low. See https://www.tecmint.com/increase-set-open-file-limits-in-linux/ for simple ways to remedy this on Linux.

**Comment by msmanui** [comment]
This are my currents values, so its that related?

```
cat /proc/sys/fs/file-max
9223372036854775807
```
```
 ulimit -Hn
1048576
```
```
ulimit -Sn
1024
```

**Comment by Jikoo** [comment]
Raising the soft limit of 1024 should solve the problem for you at least as a bandaid, yeah. Here it wasn't even Regionerator technically, it just happens to be the straw that breaks your server's back because it should be doing a lot better job not consuming so many threads.

**Comment by msmanui** [comment]
Okay. In my other machine i have this values for one of my users, can i use this same values? 
/etc/security/limits.conf:
```
mc               hard    nofile          65535
mc               soft    nofile          65535
mc              hard    nproc          unlimited
mc               soft    nproc         unlimited
kernel.pid_max = 4194304
```

**Comment by Jikoo** [comment]
That should work from the looks of it, Even doubling to 2048 would probably be more than enough for normal usage. The issue (at least, the issue I can address in terms of thread consumption) is Regionerator starting a new thread each time a chunk freshly generates to flag it. It doesn't keep the threads going, but my guess would be that for a lot of players it generates far too many individual threads during exploration when combined with your other SQL thread pools and whatnot. I can fix that so it only schedules one task at a time there and pools the submissions, but the rest of the thread usages in the plugin are pretty locked down already.

If you're still seeing problems once I fix this, Regionerator should only be consuming a couple threads. The deletion process uses 1, saving will use 2-3 depending on situation, and loading may consume another situationally from what I remember. I'll verify that before I actually close this, but when I do, if you're still seeing high thread consumption you'll likely need to look to other plugins.

**Comment by msmanui** [comment]
Do you have any ETA for the fix?

**Comment by msmanui** [comment]
Any news? As i really need it.

**Comment by Jikoo** [comment]
Sorry, for some reason your last message didn't seem to generate a notification for me.

So, for clarity, you still see issues even with a raised limit?

**Comment by msmanui** [comment]
I will test today and tell you.

**Comment by msmanui** [comment]
It wont influent that it has the old database of the regions? Should i delete that start a fresh one?

**Comment by Jikoo** [comment]
You can leave it, but you should delete the data.yml so the gather period restarts.

**Comment by msmanui** [comment]
Is still happening but now the server when doing automatic restarts, it get freeze and it doesnt restart. I only put regionator.jar in survival1 and it did only happend there. Not in the others survivals-

```
[00:10:31] [Server thread/INFO]: Saving worlds
[00:10:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[m1]'/minecraft:overworld
```

**Comment by msmanui** [comment]
Any news?

**Comment by msmanui** [comment]
Hi there! I would like to know if this issue is going to be fix.

**Comment by msmanui** [comment]
Hi! Sorry for insisting but do you have any ETA for the fix? I would be grateful if you could tell me. Thanks in advance.

**Comment by Jikoo** [comment]
No, I don't have an ETA, sorry. I don't do deadlines for hobby projects and I've been painfully busy lately. Frankly, Regionerator updates are generally very slow; it was written out of necessity (the plugin I was using for its functionality was discontinued and its posting removed) and is not a passion project, unlike most of my other works.

If you do decide to take matters into your own hands, I pushed my initial work for async batching to my collection of utilities on its own branch here: https://github.com/Jikoo/PlanarWrappers/blob/dev/async-batch/src/main/java/com/github/jikoo/planarwrappers/scheduler/AsyncBatch.java
This will be the basis for any solution I implement.

**Comment by msmanui** [comment]
I've sent you a email with an offer.

**Comment by Jikoo** [comment]
Pushed b6006562309c0f6379278e91b91754c8bd9815e3, https://ci.appveyor.com/project/Jikoo/regionerator/builds/45333069/artifacts
It's entirely untested, would probably run it on a test server first to make sure it actually flags during chunk generation.

**Comment by msmanui** [comment]
Hi, server lagged with dump thread with this: 

https://pastebin.com/JeeXjMzx

**Comment by msmanui** [comment]
I have 4 survivals, all were deleting at the same time, in the same machine but it only created this dump thread lag in one, the other 3 didnt crash or didnt cause any issues.

**Comment by Jikoo** [comment]
Honestly at this point I doubt Regionerator is the major source of your thread consumption because most of deletion is primarily single-threaded.
Threads:
1) Deletion
   - Uses a thread from `ForkJoinPool#commonPool` via Bukkit's async scheduler
2) Cache fetch for deletion
   - Uses a thread from `ForkJoinPool#commonPool` via `CompletableFuture#runAsync`
   - Limit 1 active (performed blocking deletion thread)
     - Does hit pretty fast, possible area for improvement with my own thread pool (or exposing a blocking query for async usage so as to not consume another thread at all)
3) Chunk generation
   - Uses a thread from `ForkJoinPool#commonPool` via Bukkit's async scheduler
   - Limit 1 active
4) Cache cleanup
   - Uses an unpooled thread
   - Limit 1 active

**Comment by msmanui** [comment]
Hi!
Lately, plugins seems to be working fine. I'm currently using it in 17.1.1 | However, in 1.19.3 should work still the same? Or there is any possible changes that could affect some tasks? As you know, in 1.18 they introduce the caves.

**Comment by msmanui** [comment]
Hi!
Thanks for your time and help. Lately, plugins seems to be working correctly. I'm currently using it in 17.1.1 | However, in 1.19.3 should work still the same? Or there is any possible changes that could affect some tasks? As you know, in 1.18 they introduce the caves.

**Comment by Jikoo** [comment]
Should be fine - unless Mojang drastically changes the save format, Regionerator should be able to work.

Essentially, when Regionerator rewrites a region file to delete a chunk, all it's doing is clearing the section of the table that tells the server where the chunk data is kept in the file. None of the other contents need to be parsed or touched. The server handles actually removing the orphaned chunk data the next time it loads that region. In the case of a full region deletion, Regionerator deletes the region file wholesale. As long as your world is saved in the Anvil format and Regionerator can locate the region files, it should be able to function. This is also why Regionerator doesn't *guarantee* deletion - anything loaded into memory by the server will overwrite Regionerator's changes, which can include other chunks in the same region being loaded or in the save queue.

**Comment by msmanui** [comment]
Okay thanks! 
But i still have some doubts about how the plugins works.

If i have `days-till-flag-expires: 1`

If i have a chunk with a house but i ONLY visit the house daily, will be deleted? Or do i have to modify the chunk (placing a block or modifying a chest) in order NOT to be deleted

**Comment by Jikoo** [comment]
Most of that is covered in the configuration page of the wiki https://github.com/Jikoo/Regionerator/wiki/Configuration#flagging
That would grant you 24 hours to log in and be present during a flagging interval, which occurs spread over a configured period.
If you visited it at 9 one day and then didn't log in until 10 the next day, it would have been eligible for delete for 1 hour. Whether it actually got deleted in that time would be dependent on how frequently deletion runs and how unlucky you happened to be.

**Comment by msmanui** [comment]
Quite didnt understand. If you modify that chunk by placing a block once per day, it would never delete?
