### ISSUE TITLE
Deleting old chunks based on inhabited time.

### ISSUE THREAD

**Issue by Olly32** [Jikoo/Regionerator#15]
Ok so, I'm really not sure if this is the place to be asking this, but when I saw that regionerator is able to delete old chunks post aquatic I was kinda shocked, this was after being told by md5 that it's not practical with the new region file system (https://hub.spigotmc.org/jira/browse/SPIGOT-5374) . Ok so basically, I have a world that is 300gb+ in size and I would like to be able to flag all the chunks within a set radius if they haven't been loaded in more than 2 weeks and have an inhabited time under 1800 (30 mins). The only way this seems possible is through mcaeditor but it would require quite a few hours of server downtime and a plugin would be a lot more convenient. I made a plugin myself that flags the chunks, the only problem is despite searching far and wide, there doesn't seem to be a way I know to delete chunks in 1.14. What I'm proposing is that you perhaps make an API for deleting chunks the way you do it? So that I can reduce my world size :). Sorry if this is poorly written as I am rather tired. Thanks.

**Comment by Jikoo** [comment]
If you're interested in implementing your own plugin, the meat is currently located [here](https://github.com/Jikoo/Regionerator/blob/63446e23a3de0d82ebece483115e361e4b6c34a0/src/main/java/com/github/jikoo/regionerator/util/AnvilRegion.java#L77-L121).
If all 1024 chunks are eligible for deletion, the region file is deleted. If not all are eligible, the pointers for chunks are wiped. The chunk data is not actually removed from disk until the region is loaded and rewritten by the server, the only thing that is changed is the information that tells the server where in the file the chunk's data is. Structure data is also not reset, meaning chunks deleted in this fashion often do not generate structures or contain empty loot chests, things of that nature. It's good for wide resets, not fine-grained fixes.

Any region file that has chunks currently loaded often rejects changes as of 1.13+ where before it usually would succeed. I do eventually want to offer solutions with higher success rates, but that's a ways (read: years) down the road with the amount of time I have to devote to plugin development these days. I would not wait on me if I were you.

**Comment by Olly32** [comment]
Ok, thank you for this information. Do you think that it is possible to delete the data files that tell the world a structure has been generated at a location? I don't know much about it but believe it's stored in separate .dat files.

**Comment by Jikoo** [comment]
I looked into this a while ago when someone had issues with chests not generating loot, see my [reply on Spigot](https://www.spigotmc.org/threads/regionerator.92022/page-8#post-2297385).

**Comment by Olly32** [comment]
thank you
