### ISSUE TITLE
Compiling 

### ISSUE THREAD

**Issue by Kyrobi** [Jikoo/Regionerator#16]
Hello, would you be able to compile the latest commit for Regionerator for me? I, unfortunately, do not have all the paid plugins are that required (API). 

Currently, the chunk flagging runnable is a little laggy on my server. I was hoping to try the latest commit to test if it's any better. 

Thanks!

**Comment by Jikoo** [comment]
The one commit since beta 3 only shifts some load off the main thread for deletion, nothing has changed with flagging. If you could provide me with timings that could help me track down issues with flagging, it really shouldn't be very heavy.

**Comment by Kyrobi** [comment]
https://timings.aikar.co/?id=2ac63ef4db8649ae9086be722064ae51#plugins

From 7:59 - 8:05

**Comment by Jikoo** [comment]
You should update to beta 3, 1.5.5 is pretty old.

**Comment by Kyrobi** [comment]
Oh wow. I didn't realize I was this behind on updates. Thanks for your time! I'll reopen the issue of flagging continues to be the problem.

**Comment by Jikoo** [comment]
The conversion to SQLite is decently heavy and may take some time, so your first run's results are likely not going to be a great indicator of performance.
