### ISSUE TITLE
 Text file busy

### ISSUE THREAD

**Issue by MaksymSemenykhin** [Jikoo/Regionerator#209]
I am getting errors after some time wth this plugin 

minecraft    | [17:35:44 INFO]: [Regionerator] Deletion cycle complete for world_the_end: checked 4, deleted 0 regions & 1392 chunks
minecraft    | [17:36:35 INFO]: [Regionerator] Deletion run scheduled for world_nether
minecraft    | [17:36:35 WARN]: [Regionerator] Caught an IOException attempting to populate chunk data: ./world_nether/DIM-1/entities/r.-1.-1.mca: Text file busy
minecraft    | java.nio.file.FileSystemException: ./world_nether/DIM-1/entities/r.-1.-1.mca: Text file busy
minecraft    |  at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
minecraft    |  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
minecraft    |  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
minecraft    |  at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248) ~[?:?]
minecraft    |  at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110) ~[?:?]
minecraft    |  at java.nio.file.Files.deleteIfExists(Files.java:1191) ~[?:?]
minecraft    |  at com.github.jikoo.regionerator.world.impl.AnvilRegion.write(AnvilRegion.java:217) ~[Regionerator.jar:?]
minecraft    |  at com.github.jikoo.regionerator.world.impl.AnvilRegion.write(AnvilRegion.java:161) ~[Regionerator.jar:?]
minecraft    |  at com.github.jikoo.regionerator.DeletionRunnable.handleRegion(DeletionRunnable.java:124) ~[Regionerator.jar:?]
minecraft    |  at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
minecraft    |  at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
minecraft    |  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
minecraft    |  at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174) ~[?:?]
minecraft    |  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
minecraft    |  at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
minecraft    |  at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
minecraft    |  at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
minecraft    |  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
minecraft    |  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
minecraft    |  at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
minecraft    |  at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
minecraft    |  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
minecraft    |  at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
minecraft    |  at com.github.jikoo.regionerator.DeletionRunnable.run(DeletionRunnable.java:56) ~[Regionerator.jar:?]
minecraft    |  at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-318]
minecraft    |  at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-318]
minecraft    |  at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]
minecraft    |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
minecraft    |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
minecraft    |  at java.lang.Thread.run(Thread.java:833) ~[?:?]
minecraft    | [17:36:36 WARN]: [Regionerator] Caught an IOException attempting to populate chunk data: ./world_nether/DIM-1/entities/r.-1.0.mca: Text file busy
minecraft    | java.nio.file.FileSystemException: ./world_nether/DIM-1/entities/r.-1.0.mca: Text file busy
minecraft    |  at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
minecraft    |  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
minecraft    |  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
minecraft    |  at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248) ~[?:?]
minecraft    |  at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110) ~[?:?]
minecraft    |  at java.nio.file.Files.deleteIfExists(Files.java:1191) ~[?:?]
minecraft    |  at com.github.jikoo.regionerator.world.impl.AnvilRegion.write(AnvilRegion.java:217) ~[Regionerator.jar:?]
minecraft    |  at com.github.jikoo.regionerator.world.impl.AnvilRegion.write(AnvilRegion.java:161) ~[Regionerator.jar:?]
minecraft    |  at com.github.jikoo.regionerator.DeletionRunnable.handleRegion(DeletionRunnable.java:124) ~[Regionerator.jar:?]
minecraft    |  at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
minecraft    |  at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
minecraft    |  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
minecraft    |  at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174) ~[?:?]
minecraft    |  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
minecraft    |  at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
minecraft    |  at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
minecraft    |  at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
minecraft    |  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
minecraft    |  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
minecraft    |  at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
minecraft    |  at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
minecraft    |  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
minecraft    |  at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
minecraft    |  at com.github.jikoo.regionerator.DeletionRunnable.run(DeletionRunnable.java:56) ~[Regionerator.jar:?]
minecraft    |  at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-318]
minecraft    |  at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-318]
minecraft    |  at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]
minecraft    |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
minecraft    |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
minecraft    |  at java.lang.Thread.run(Thread.java:833) ~[?:?]
minecraft    | [17:36:41 INFO]: [Regionerator] Deletion cycle complete for world_nether: checked 10, deleted 6 regions & 1117 chunks

mc - paper-1.20.2-318 docker based
no other plugin used

**Comment by Jikoo** [comment]
That particular error looks like it can be ignored, should be a simple fix to just not print that particular exception.
The goal is to always let conflicts cause Regionerator to fail to delete/rewrite in case the area is actively being visited, and most IO exceptions do need to be printed in case of file permission problems, disk space, etc.

**Comment by MaksymSemenykhin** [comment]
> That particular error looks like it can be ignored, should be a simple fix to just not print that particular exception. The goal is to always let conflicts cause Regionerator to fail to delete/rewrite in case the area is actively being visited, and most IO exceptions do need to be printed in case of file permission problems, disk space, etc.

not sure, because it seems like it do not remove chunks. This erros pops up constantly

**Comment by MaksymSemenykhin** [comment]
And, I think , after those I am  getting `chunk remap` error in viaversion

**Comment by MaksymSemenykhin** [comment]
> > not sure, because it seems like it do not remove chunks. This erros pops up constantly
> 
> Yes, Regionerator cannot rewrite or delete the file if it is in use. If the file is delete-eligible, Regionerator will try again next run. Regionerator is designed to fail in the event of a conflict, it is not supposed to delete in cases like this.
> 
> > And, I think , after those I am getting `chunk remap` error in viaversion
> 
> Anything in ViaVersion is very unlikely to be related to Regionerator; it operates on external files, not in-memory chunks.

okay, I guess)

**Comment by Jikoo** [comment]
Addressed by fcc203fce9f044a5d4057720c3eda80879801dcf.
