### ISSUE TITLE
Feature | Add a protection radius around a protected area

### ISSUE THREAD

**Issue by Corenb** [Jikoo/Regionerator#26]
Hi,

I guess this feature can be helpful if like me you are using EWG and you modify your biomes settings (biomes regenerated no longer match with old biomes). So to avoid player have their claims inside a completely regenerated area, it's can be useful to defined a protection radius around the player protected area ?

**Comment by Jikoo** [comment]
This would either be horrendously inefficient or require me to re-implement every single protection plugin hooked.
