### ISSUE TITLE
Towny hook not working

### ISSUE THREAD

**Issue by gerardvanschip** [Jikoo/Regionerator#3]
When I do /regionerator check it tells me that towny is not protecting anything. Worldguard works ok.

This is a huge showstopper for me.

**Comment by Jikoo** [comment]
Do you have a custom cell size other than 16?

**Comment by gerardvanschip** [comment]
Indeed, mine is set to 8x8 to give people more flexibility with their town plots. I just ran your updated build and it now says its protected. I'm curious how it functions. Does a 8x8 towny chunk being claimed flag the whole 16x16 minecraft chunk?

**Comment by Jikoo** [comment]
Previously the check operated under the assumption that all cells were a chunk, which lead to incorrect cells being checked. It still needs a little tweaking to ensure that all possible cells inside a chunk are checked, but that's easy from here.

**Comment by gerardvanschip** [comment]
Sweet, the plan is to go live with this plugin on the 1st of April. I'm testing it on a full copy of my server on my local machine. I look forward to install this. My purpose is getting rid of deserted builds and regeneration of resources of abandoned strip mining operations.

**Comment by Jikoo** [comment]
All right, [1.4.4](https://github.com/Jikoo/Regionerator/releases/tag/1.4.4) should be a full fix. The flaw with the quick dev build I had you test was that it would only check the lowest cell in a chunk, 1.4.4 should check every cell.
