### ISSUE TITLE
1.7.10 error

### ISSUE THREAD

**Issue by Portanna** [Jikoo/Regionerator#5]
> [07:09:25 WARN]: [Regionerator] Task #5437 for Regionerator v1.4.4 generated an exception
> java.lang.NoSuchFieldError: SPECTATOR
>         at com.github.jikoo.regionerator.FlaggingRunnable.run(FlaggingRunnable.java:25) ~[?:?]
>         at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[paper1710.jar:git-PaperSpigot-1f7d532]
>         at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [paper1710.jar:git-PaperSpigot-1f7d532]
>         at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:701) [paper1710.jar:git-PaperSpigot-1f7d532]
>         at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [paper1710.jar:git-PaperSpigot-1f7d532]
>         at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [paper1710.jar:git-PaperSpigot-1f7d532]
>         at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [paper1710.jar:git-PaperSpigot-1f7d532]
>         at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [paper1710.jar:git-PaperSpigot-1f7d532]

**Comment by Jikoo** [comment]
Hm, not sure how I want to handle detecting versions without spectate gamemode. Thanks for letting me know, I'll get to it sometime this week hopefully.

**Comment by Portanna** [comment]
Any news?

**Comment by Jikoo** [comment]
If you would please, try [this version](https://github.com/Jikoo/Regionerator/files/1151068/Regionerator.zip), just change the extension to jar.

**Comment by Jikoo** [comment]
[1.5.0](https://github.com/Jikoo/Regionerator/releases/tag/1.5.0)
