### ISSUE TITLE
hi im very new and need help with the config

### ISSUE THREAD

**Issue by dre232132** [Jikoo/Regionerator#53]
i was wondering if you could send me a default config with world, world_nether and world_the_end enabled and i could just copy and paste it in

**Comment by Jikoo** [comment]
Sorry, no. For starters, I don't know whether you're running the dev build or the current release. For dev build documentation, the wiki is up-to-date. For the current 2.2.1 release, see [here](https://github.com/Jikoo/Regionerator/wiki/Configuration/f8471f267d9a1127f078b37d13c7a68bbc8008cf#worlds).

In addition to that, Regionerator is a very niche plugin. If you don't know what you're doing you can wreck your server. If you don't have the ability to configure the plugin yourself, you probably haven't configured backups or anything else that could help you out.
