### ISSUE TITLE
FastAsyncWorldedit Compatibility

### ISSUE THREAD

**Issue by Drc-DEV** [Jikoo/Regionerator#7]
When using FastAsyncWorldedit and FAWE-Worldguard 7, this error shows up and Regionerator does not load. Maybe the problem is on FAWE's side, but you could add compatibility for FAWE worldguard eventually.
FAWE WorldEdit: https://ci.athion.net/job/FAWE-1.13/
FAWE WorldGuard: https://ci.athion.net/job/FAWE-WorldGuard-1.13/

Error:
https://pastebin.com/Z8507Bgt

**Comment by Jikoo** [comment]
That appears to just be WG, which has been a little unstable lately. I'll have a look.

**Comment by Jikoo** [comment]
Does Regionerator load before FAWE by any chance? I just checked out the latest FAWE-1.13, and it does contain the exception class.

**Comment by Drc-DEV** [comment]
Yeah I'll try with latest version. The version I was using at the time of the post is largely filled with bugs.
