### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by coco0325** [Jikoo/Regionerator#78]
Error: https://pastebin.com/MsxicifR
It happened after I upgrade Tuinity to the latest version.

**Comment by Jikoo** [comment]
You appear to have no worlds loaded.

This isn't something that really needs to be addressed on my end - it's impossible to have a server with no worlds loaded, which means that my load order (specifically unspecified that should fall through to the default of post-world) is not being respected by the server implementation.

I could certainly apply a hacky workaround for it, but then the enable process becomes even more of a back and forth juggling mess than it already is.
