### ISSUE TITLE
Chunks not regenerating properly

### ISSUE THREAD

**Issue by melinstagibson** [Jikoo/Regionerator#8]
It seems like the terrain that gets newly generated only works properly when you delete the entire region.

I updated a 1.12 map to 1.13 and then ran regionerator. the regions that were completeley removed regenerated fine, regions where it only deleted specific chunks regenerated chunks using seemingly the wrong biomes, even if only one chunk in that region was left out. 
Is there a way to fix this?

https://imgur.com/a/v5gN0QO

**Comment by Leomixer17** [comment]
@melinstagibson It's just that your world were generated in an old version (<1.13), so the chunks were replaced with the new version of the biomes

**Comment by Jikoo** [comment]
Seems like individual chunks have been struggling to save in 1.13+. I'm going to close this as Regionerator has never guaranteed chunk deletion, only a "best effort" approach. I am looking to provide better support for this in 2.0.0, but as this is one of many hobby projects for me, it may take a couple of years to finish.
