### ISSUE TITLE
Don't rely on Bukkit softdepend system

### ISSUE THREAD

**Issue by HollishKid** [Jikoo/Regionerator#85]
Hello,

First of, thanks for your plugin, I love the pure, simple, and yet strong concept.
Now, to the issue: Lands is not correctly integrating.
Here are the details of the server I ran this on:

Paper: `git-Paper-777 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`
Lands: `Version: 5.12.5`
Regionerator: `v2.3.0` (which I got here: https://ci.appveyor.com/project/Jikoo/regionerator/builds/39982168/artifacts)

Thanks for considering this issue!

**Comment by Jikoo** [comment]
Please include startup logs on `MEDIUM` or higher debug - I don't own a copy of Lands, so I can't replicate setups.

**Comment by HollishKid** [comment]
My bad, please find it here: https://pastebin.com/0yu0HvDk
This log was generated with `debug-level: HIGH`.

**Comment by Jikoo** [comment]
Ah okay, you appear to have a set of plugins causing a circular dependency, which then disables Bukkit's softdepend system for plugin dependencies. Been meaning to address this for a while, good to have a reminder.

Here's a workaround:
- Change the archive's filetype from `jar` to `zip`
- Extract `plugin.yml`
- Remove Lands from the `softdepend` list
- Add in a new `depend` section containing Lands, i.e. `depend: [ Lands ]`
- Replace `plugin.yml` in the archive with your modified version
- Change the archive's filetype back to `jar` from `zip`

**Comment by HollishKid** [comment]
The workaround seems to have worked!
Thanks for your help!
